package com.sxgy.sp52.core.pojo;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   系统使用的角色ROLE_XXX
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sp52_role
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@ApiModel(value = "Sp52Role系统角色表")
public class Sp52Role implements Serializable {
    /**
     * Database Column Remarks:
     *   角色id
     */
    @TableId(type = IdType.AUTO)
    @ApiModelProperty(name = "id", value = "角色表主键", dataType = "Long")
    private Long id;

    /**
     * Database Column Remarks:
     *   角色名称
     */
    @ApiModelProperty(name = "roleName", value = "角色名称", dataType = "String")
    private String roleName;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    @ApiModelProperty(name = "createTime", value = "创建时间", dataType = "java.util.Date")
    private Date createTime;

    /**
     * Database Column Remarks:
     *   状态：1正常，0禁用，-1停用
     */
    @ApiModelProperty(name = "roleState", value = "状态", dataType = "Byte")
    private Byte roleState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sp52_role
     *
     * @mbg.generated Sat Nov 23 14:49:40 CST 2019
     */
    private static final long serialVersionUID = 1L;
}