package com.sxgy.sp52.core.pojo;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   管理员表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sp52_admin
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@ApiModel(value = "Sp52Admin管理员表")
public class Sp52Admin implements Serializable {
    /**
     * Database Column Remarks:
     *   管理员id
     */
    @ApiModelProperty(name = "id", value = "管理员主键", dataType = "Long")
    @TableId(type = IdType.AUTO)
    private Long id;

    /**
     * Database Column Remarks:
     *   用户名
     */
    @ApiModelProperty(name = "username", value = "用户名", dataType = "String")
    private String username;

    /**
     * Database Column Remarks:
     *   密码
     */
    @ApiModelProperty(name = "password", value = "密码", dataType = "String")
    private String password;

    /**
     * Database Column Remarks:
     *   盐值
     */
    @ApiModelProperty(name = "saltValue", value = "盐值", dataType = "String")
    private String saltValue;

    /**
     * Database Column Remarks:
     *   管理员工号
     */
    @ApiModelProperty(name = "operatorId", value = "管理员工号", dataType = "Long")
    private Long operatorId;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    @ApiModelProperty(name = "createTime", value = "创建时间", dataType = "java.util.Date")
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     */
    @ApiModelProperty(name = "updateTime", value = "修改时间", dataType = "java.util.Date")
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   状态：1正常，0禁用，-1停用
     */
    @ApiModelProperty(name = "status", value = "状态", dataType = "Byte")
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sp52_admin
     *
     * @mbg.generated Sat Nov 23 14:49:40 CST 2019
     */
    private static final long serialVersionUID = 1L;
}