package com.sxgy.sp52.core.pojo;

import java.io.Serializable;

/**
 * Database Table Remarks:
 *   学生基本信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sp52_student
 */
public class Sp52Student implements Serializable {
    /**
     * Database Column Remarks:
     *   学号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp52_student.id
     *
     * @mbg.generated Sat Nov 23 14:49:40 CST 2019
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp52_student.stu_name
     *
     * @mbg.generated Sat Nov 23 14:49:40 CST 2019
     */
    private String stuName;

    /**
     * Database Column Remarks:
     *   性别：男，女，X
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp52_student.stu_sex
     *
     * @mbg.generated Sat Nov 23 14:49:40 CST 2019
     */
    private String stuSex;

    /**
     * Database Column Remarks:
     *   年龄
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp52_student.stu_age
     *
     * @mbg.generated Sat Nov 23 14:49:40 CST 2019
     */
    private Integer stuAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sp52_student
     *
     * @mbg.generated Sat Nov 23 14:49:40 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp52_student.id
     *
     * @return the value of sp52_student.id
     *
     * @mbg.generated Sat Nov 23 14:49:40 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp52_student.id
     *
     * @param id the value for sp52_student.id
     *
     * @mbg.generated Sat Nov 23 14:49:40 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp52_student.stu_name
     *
     * @return the value of sp52_student.stu_name
     *
     * @mbg.generated Sat Nov 23 14:49:40 CST 2019
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp52_student.stu_name
     *
     * @param stuName the value for sp52_student.stu_name
     *
     * @mbg.generated Sat Nov 23 14:49:40 CST 2019
     */
    public void setStuName(String stuName) {
        this.stuName = stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp52_student.stu_sex
     *
     * @return the value of sp52_student.stu_sex
     *
     * @mbg.generated Sat Nov 23 14:49:40 CST 2019
     */
    public String getStuSex() {
        return stuSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp52_student.stu_sex
     *
     * @param stuSex the value for sp52_student.stu_sex
     *
     * @mbg.generated Sat Nov 23 14:49:40 CST 2019
     */
    public void setStuSex(String stuSex) {
        this.stuSex = stuSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp52_student.stu_age
     *
     * @return the value of sp52_student.stu_age
     *
     * @mbg.generated Sat Nov 23 14:49:40 CST 2019
     */
    public Integer getStuAge() {
        return stuAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp52_student.stu_age
     *
     * @param stuAge the value for sp52_student.stu_age
     *
     * @mbg.generated Sat Nov 23 14:49:40 CST 2019
     */
    public void setStuAge(Integer stuAge) {
        this.stuAge = stuAge;
    }
}