package com.sxgy.sp52.core.pojo;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   模块资源表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sp52_modular
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@ApiModel(value = "Sp52Modular模块表")
public class Sp52Modular implements Serializable {
    /**
     * Database Column Remarks:
     *   模块id
     */
    @ApiModelProperty(name = "id", value = "模块表主键", dataType = "Long")
    private Long id;

    /**
     * Database Column Remarks:
     *   页面描述
     */
    @ApiModelProperty(name = "pageName", value = "页面描述", dataType = "String")
    private String pageName;

    /**
     * Database Column Remarks:
     *   页面URL
     */
    @ApiModelProperty(name = "pageUrl", value = "页面URL", dataType = "String")
    private String pageUrl;

    /**
     * Database Column Remarks:
     *   请求方式
     */
    @ApiModelProperty(name = "pageMethod", value = "请求方式", dataType = "String")
    private String pageMethod;

    /**
     * Database Column Remarks:
     *   页面层次：1一级目录，2二级目录，3三级目录，0请求
     */
    @ApiModelProperty(name = "pageCatalog", value = "页面层次", dataType = "Byte")
    private Byte pageCatalog;

    /**
     * Database Column Remarks:
     *   父模块
     */
    @ApiModelProperty(name = "parentId", value = "父模块", dataType = "Long")
    private Long parentId;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    @ApiModelProperty(name = "createTime", value = "创建时间", dataType = "java.util.Date")
    private Date createTime;

    /**
     * Database Column Remarks:
     *   状态：1正常，0禁用，-1停用
     */
    @ApiModelProperty(name = "modularState", value = "状态", dataType = "Byte")
    private Byte modularState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sp52_modular
     */
    private static final long serialVersionUID = 1L;
}