package com.sxgy.sp52.core.pojo;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

/**
 * Database Table Remarks:
 *   学生基本信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sp52_student
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@ApiModel(value = "Sp52Student学生表")
public class Sp52Student implements Serializable {
    /**
     * Database Column Remarks:
     *   学号
     */
    @ApiModelProperty(name = "id",value = "学号", dataType = "java.lang.Long")
    @TableId(type = IdType.AUTO)
    private Long id;

    /**
     * Database Column Remarks:
     *   姓名
     */
    @ApiModelProperty(name = "stuName", value = "姓名", dataType = "java.lang.String")
    private String stuName;

    /**
     * Database Column Remarks:
     *   性别：男，女，X
     */
    @ApiModelProperty(name = "stuSex", value = "性别：男，女，X", dataType = "java.lang.String")
    private String stuSex;

    /**
     * Database Column Remarks:
     *   年龄
     */
    @ApiModelProperty(name = "stuAge", value = "年龄", dataType = "java.lang.Integer")
    private Integer stuAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sp52_student
     *
     * @mbg.generated Sat Nov 23 14:49:40 CST 2019
     */
    private static final long serialVersionUID = 1L;
}