package com.sxgy.sp52.core.pojo;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   操作日志
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sp52_log
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@ApiModel(value = "Sp52Log操作日志")
public class Sp52Log implements Serializable {
    /**
     * Database Column Remarks:
     *   日志表主键
     */
    @ApiModelProperty(name = "id", value = "日志表主键", dataType = "java.lang.Long")
    private Long id;

    /**
     * Database Column Remarks:
     *   操作员编号，管理员表主键
     */
    @ApiModelProperty(name = "operatorId", value = "操作员编号，管理员表主键", dataType = "java.lang.Long")
    private Long operatorId;

    /**
     * Database Column Remarks:
     *   操作员姓名
     */
    @ApiModelProperty(name = "operatorName", value = "操作员姓名", dataType = "java.lang.String")
    private String operatorName;

    /**
     * Database Column Remarks:
     *   操作模块
     */
    @ApiModelProperty(name = "logName", value = "操作模块", dataType = "java.lang.String")
    private String logName;

    /**
     * Database Column Remarks:
     *   操作内容
     */
    @ApiModelProperty(name = "logValue", value = "操作内容", dataType = "java.lang.String")
    private String logValue;

    /**
     * Database Column Remarks:
     *   操作结果
     */
    @ApiModelProperty(name = "logState", value = "操作结果", dataType = "java.lang.String")
    private String logState;

    /**
     * Database Column Remarks:
     *   操作时间
     */
    @ApiModelProperty(name = "logTime", value = "操作时间", dataType = "java.util.Date")
    private Date logTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sp52_log
     *
     * @mbg.generated Fri Nov 29 18:30:59 CST 2019
     */
    private static final long serialVersionUID = 1L;
}