package com.sxgy.sp52.core.pojo;

import java.io.Serializable;

/**
 * Database Table Remarks:
 *   管理员角色联系表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sp52_admin_role
 */
public class Sp52AdminRole implements Serializable {
    /**
     * Database Column Remarks:
     *   管理员-角色表id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp52_admin_role.id
     *
     * @mbg.generated Sat Nov 23 14:49:40 CST 2019
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   管理员id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp52_admin_role.admin_id
     *
     * @mbg.generated Sat Nov 23 14:49:40 CST 2019
     */
    private Long adminId;

    /**
     * Database Column Remarks:
     *   角色id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp52_admin_role.role_id
     *
     * @mbg.generated Sat Nov 23 14:49:40 CST 2019
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sp52_admin_role
     *
     * @mbg.generated Sat Nov 23 14:49:40 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp52_admin_role.id
     *
     * @return the value of sp52_admin_role.id
     *
     * @mbg.generated Sat Nov 23 14:49:40 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp52_admin_role.id
     *
     * @param id the value for sp52_admin_role.id
     *
     * @mbg.generated Sat Nov 23 14:49:40 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp52_admin_role.admin_id
     *
     * @return the value of sp52_admin_role.admin_id
     *
     * @mbg.generated Sat Nov 23 14:49:40 CST 2019
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp52_admin_role.admin_id
     *
     * @param adminId the value for sp52_admin_role.admin_id
     *
     * @mbg.generated Sat Nov 23 14:49:40 CST 2019
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp52_admin_role.role_id
     *
     * @return the value of sp52_admin_role.role_id
     *
     * @mbg.generated Sat Nov 23 14:49:40 CST 2019
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp52_admin_role.role_id
     *
     * @param roleId the value for sp52_admin_role.role_id
     *
     * @mbg.generated Sat Nov 23 14:49:40 CST 2019
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}