package com.sxgy.sp52.core.pojo;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sp_student
 */
public class SpStudent implements Serializable {
    /**
     * Database Column Remarks:
     *   学号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_student.stu_id
     *
     * @mbg.generated
     */
    private Long stuId;

    /**
     * Database Column Remarks:
     *   姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_student.stu_name
     *
     * @mbg.generated
     */
    private String stuName;

    /**
     * Database Column Remarks:
     *   性别：男，女，X
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_student.stu_sex
     *
     * @mbg.generated
     */
    private String stuSex;

    /**
     * Database Column Remarks:
     *   年龄
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_student.stu_age
     *
     * @mbg.generated
     */
    private Integer stuAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sp_student
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_student.stu_id
     *
     * @return the value of sp_student.stu_id
     *
     * @mbg.generated
     */
    public Long getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_student.stu_id
     *
     * @param stuId the value for sp_student.stu_id
     *
     * @mbg.generated
     */
    public void setStuId(Long stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_student.stu_name
     *
     * @return the value of sp_student.stu_name
     *
     * @mbg.generated
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_student.stu_name
     *
     * @param stuName the value for sp_student.stu_name
     *
     * @mbg.generated
     */
    public void setStuName(String stuName) {
        this.stuName = stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_student.stu_sex
     *
     * @return the value of sp_student.stu_sex
     *
     * @mbg.generated
     */
    public String getStuSex() {
        return stuSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_student.stu_sex
     *
     * @param stuSex the value for sp_student.stu_sex
     *
     * @mbg.generated
     */
    public void setStuSex(String stuSex) {
        this.stuSex = stuSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_student.stu_age
     *
     * @return the value of sp_student.stu_age
     *
     * @mbg.generated
     */
    public Integer getStuAge() {
        return stuAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_student.stu_age
     *
     * @param stuAge the value for sp_student.stu_age
     *
     * @mbg.generated
     */
    public void setStuAge(Integer stuAge) {
        this.stuAge = stuAge;
    }
}