server:
  port: 8081
spring: 
  datasource:     url: jdbc:mysql://127.0.0.1:3306/springdata2?serverTimezone=GMT%2B8
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 20
      initial-size: 10
      max-idle: 8
      min-idle: 8
  thymeleaf:    prefix: classpath:/templates/
    suffix: .html
