package com.sxgy.sp52.core.mapper;

import com.sxgy.sp52.core.pojo.SpAdmin;

public interface SpAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_admin
     *
     * @mbg.generated
     */
    Long insertReturnKey(SpAdmin record);
    SpAdmin findByName(SpAdmin admin);
}