package com.sxgy.sp52.core.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.sxgy.sp52.core.pojo.SpStudent;

public interface SpStudentMapper extends BaseMapper<SpStudent> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_student
     *
     * @mbg.generated
     */
    Long insertReturnKey(SpStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_student
     *
     * @mbg.generated
     */
    Long insertSelectiveReturnKey(SpStudent record);
}